export const ROUTES = {
  home: '/',
  parceiros: '/parceiros',
  orgaos: '/orgaos',
  quemSomos: '/quem-somos',
  precos: '/precos',
  contato: '/contato',
  login: '/login',
  cadastro: '/cadastro',
  criarConta: '/criar-conta',
  authCallback: '/auth/callback',
  esqueciMinhaSenha: '/esqueci-minha-senha',
  redefinirSenha: '/redefinir-senha',
  termosDeUso: '/termos-de-uso',
  politicaDePrivacidade: '/politica-de-privacidade',
  meuPerfil: '/meu-perfil',
  ataDetalhe: (slug: string) => `/atas/${slug}`,
  admin: '/admin',
  adminDashboard: '/admin',
  adminAtas: '/admin/atas',
  adminAtasNova: '/admin/atas/novo',
  adminAtasEditar: (id: string) => `/admin/atas/${id}/editar`,
  adminParceiros: '/admin/parceiros',
  adminParceirosNovo: '/admin/parceiros/novo',
  adminParceirosEditar: (id: string) => `/admin/parceiros/${id}/editar`,
  adminCategorias: '/admin/categorias',
  adminCategoriasNova: '/admin/categorias/novo',
  adminCategoriasEditar: (id: string) => `/admin/categorias/${id}/editar`,
  adminTipos: '/admin/tipos',
  adminTiposNovo: '/admin/tipos/novo',
  adminTiposEditar: (id: string) => `/admin/tipos/${id}/editar`,
  adminOrgaos: '/admin/orgaos',
  adminOrgaosNovo: '/admin/orgaos/novo',
  adminOrgaosEditar: (id: string) => `/admin/orgaos/${id}/editar`,
  adminUsuarios: '/admin/usuarios',
  adminUsuariosNovo: '/admin/usuarios/novo',
  adminUsuariosEditar: (id: string) => `/admin/usuarios/${id}/editar`,
  forbidden: '/403',
  notFound: '/404',
} as const
